import { Injectable } from '@angular/core';
import { Game } from '../model/interfaces/game';

@Injectable({
  providedIn: 'root'
})
export class ScheduleService {

  private testSchedule: Game[] = [
    {
      id: 0,
      week: 1,
      homeTeam: 'LAR',
      homeSpread: 3,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'BUF',
      awaySpread: -3,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/8/2022',
      startTime: '8:20 PM',
    },
    {
      id: 1,
      week: 1,
      homeTeam: 'ATL',
      homeSpread: 3,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'NO',
      awaySpread: -3,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 2,
      week: 1,
      homeTeam: 'CIN',
      homeSpread: -7,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'PIT',
      awaySpread: 7,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 4,
      week: 1,
      homeTeam: 'DET',
      homeSpread: 10,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'PHI',
      awaySpread: -10,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 5,
      week: 1,
      homeTeam: 'CHI',
      homeSpread: 6,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'SF',
      awaySpread: -6,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 6,
      week: 1,
      homeTeam: 'MIA',
      homeSpread: -3,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'NE',
      awaySpread: 3,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 7,
      week: 1,
      homeTeam: 'NYJ',
      homeSpread: -7,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'BAL',
      awaySpread: 7,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 8,
      week: 1,
      homeTeam: 'WAS',
      homeSpread: -4,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'JAX',
      awaySpread: 4,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 9,
      week: 1,
      homeTeam: 'CAR',
      homeSpread: -8,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'CLE',
      awaySpread: 8,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 10,
      week: 1,
      homeTeam: 'HOU',
      homeSpread: 9,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'IND',
      awaySpread: -9,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '1:00 PM',
    },
    {
      id: 11,
      week: 1,
      homeTeam: 'TEN',
      homeSpread: -3,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'NYG',
      awaySpread: 3,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '4:25 PM',
    },
    {
      id: 12,
      week: 1,
      homeTeam: 'MIN',
      homeSpread: -3,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'GB',
      awaySpread: 3,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '4:25 PM',
    },
    {
      id: 13,
      week: 1,
      homeTeam: 'ARI',
      homeSpread: 3,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'KC',
      awaySpread: -3,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '4:25 PM',
    },
    {
      id: 14,
      week: 1,
      homeTeam: 'LAC',
      homeSpread: -6,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'LV',
      awaySpread: 6,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '4:25 PM',
    },
    {
      id: 15,
      week: 1,
      homeTeam: 'DAL',
      homeSpread: -4,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'TB',
      awaySpread: 4,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/11/2022',
      startTime: '8:20 PM',
    },
    {
      id: 16,
      week: 1,
      homeTeam: 'SEA',
      homeSpread: -3,
      homeScore: null,
      homePickValue: null,
      awayTeam: 'DEN',
      awaySpread: 3,
      awayScore: null,
      awayPickValue: null,
      startDate: '9/12/2022',
      startTime: '8:15 PM',
    },
  ]


  constructor() { }

  // TODO - replace mock schedule data

  getSchedule(): Game[] {
    return this.testSchedule;
  }
}
